# Jumia Products Analysis

### Exploring data

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('data.csv')

In [39]:
df.head(10)

,Product_Name,Price,Old_Price,Discount,Rating
0,Aula S20 LED Macro Gaming Mouse - Black,EGP 195.00,EGP 370.50,47%,4.4 out of 5
1,Aula USB Wired Gaming Mouse - Black-2400DPI - ...,EGP 195.00,EGP 340.86,43%,4.6 out of 5
2,"HP Wireless Mouse, USB Charging, 1000 DB Senso...",EGP 250.00,EGP 499.00,50%,5 out of 5
3,"ZERO ZR-2200 Gaming Mouse 3200 DPI, 8 BUTTONS ...",EGP 175.00,EGP 199.00,12%,NaN
4,"Onikuma CW916 Gaming Mouse RGB - 7,200 DPI - 8...",EGP 350.00,EGP 450.00,22%,NaN
5,FANTECH Wg10 Raigor Ii Wireless Gaming Mouse -...,EGP 499.00,EGP 800.00,38%,4.7 out of 5
6,"ZERO ZR-1800 ZERO Gaming Mouse 3200 DPI, 6 BUT...",EGP 299.00,EGP 399.00,25%,4.3 out of 5
7,DELL Wireless Mouse Dell 3100,EGP 195.00,EGP 195.00,0%,1 out of 5
8,Gamdias Zeus E3 Gaming Optical Mouse And NYX E...,EGP 290.00,EGP 585.00,50%,4.5 out of 5
9,"ZERO ZR-2100 ZERO Gaming Mouse 3200 DPI, 6 BUT...",EGP 185.00,EGP 199.00,7%,3.3 out of 5

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_Name  80 non-null     object
 1   Price         80 non-null     object
 2   Old_Price     80 non-null     object
 3   Discount      80 non-null     object
 4   Rating        34 non-null     object
dtypes: object(5)
memory usage: 3.3+ KB

### Fix data types and Values

In [41]:
def extract_prices(price_str):
    if '-' in price_str:
        min_price, max_price = price_str.split(' - ')
        min_price = min_price.replace('EGP', '').replace(',', '').strip()
        max_price = max_price.replace('EGP', '').replace(',', '').strip()
        return pd.Series([float(min_price), float(max_price)])
    else:
        price = price_str.replace('EGP', '').replace(',', '').strip()
        return pd.Series([float(price), float(price)])

In [42]:

df[['Price_Min', 'Price_Max']] = df['Price'].apply(extract_prices)
df['Price'] = df[['Price_Min', 'Price_Max']].mean(axis=1)
df.drop(['Price_Min', 'Price_Max'], axis=1, inplace=True)

df[['Price_Min', 'Price_Max']] = df['Old_Price'].apply(extract_prices)
df['Old_Price'] = df[['Price_Min', 'Price_Max']].mean(axis=1)
df.drop(['Price_Min', 'Price_Max'], axis=1, inplace=True)


df['Discount'] = df['Discount'].str.replace('%', '').astype(float)
df['Rating'] = df['Rating'].str.replace(' out of 5', '').astype(float)

Check null values

In [43]:
df.isnull().sum()

Product_Name     0
Price            0
Old_Price        0
Discount         0
Rating          46
dtype: int64

In [44]:
df.head(10)

,Product_Name,Price,Old_Price,Discount,Rating
0,Aula S20 LED Macro Gaming Mouse - Black,195.0,370.50,47.0,4.4
1,Aula USB Wired Gaming Mouse - Black-2400DPI - ...,195.0,340.86,43.0,4.6
2,"HP Wireless Mouse, USB Charging, 1000 DB Senso...",250.0,499.00,50.0,5.0
3,"ZERO ZR-2200 Gaming Mouse 3200 DPI, 8 BUTTONS ...",175.0,199.00,12.0,NaN
4,"Onikuma CW916 Gaming Mouse RGB - 7,200 DPI - 8...",350.0,450.00,22.0,NaN
5,FANTECH Wg10 Raigor Ii Wireless Gaming Mouse -...,499.0,800.00,38.0,4.7
6,"ZERO ZR-1800 ZERO Gaming Mouse 3200 DPI, 6 BUT...",299.0,399.00,25.0,4.3
7,DELL Wireless Mouse Dell 3100,195.0,195.00,0.0,1.0
8,Gamdias Zeus E3 Gaming Optical Mouse And NYX E...,290.0,585.00,50.0,4.5
9,"ZERO ZR-2100 ZERO Gaming Mouse 3200 DPI, 6 BUT...",185.0,199.00,7.0,3.3

Fill empty rating with 0

In [45]:
df['Rating'] = df['Rating'].fillna(0)

Rename `Discount` column to `Discount_Percentage`

In [46]:
df.rename(columns={'Discount': 'Discount_Percentage'}, inplace=True)
df.head(10)

,Product_Name,Price,Old_Price,Discount_Percentage,Rating
0,Aula S20 LED Macro Gaming Mouse - Black,195.0,370.50,47.0,4.4
1,Aula USB Wired Gaming Mouse - Black-2400DPI - ...,195.0,340.86,43.0,4.6
2,"HP Wireless Mouse, USB Charging, 1000 DB Senso...",250.0,499.00,50.0,5.0
3,"ZERO ZR-2200 Gaming Mouse 3200 DPI, 8 BUTTONS ...",175.0,199.00,12.0,0.0
4,"Onikuma CW916 Gaming Mouse RGB - 7,200 DPI - 8...",350.0,450.00,22.0,0.0
5,FANTECH Wg10 Raigor Ii Wireless Gaming Mouse -...,499.0,800.00,38.0,4.7
6,"ZERO ZR-1800 ZERO Gaming Mouse 3200 DPI, 6 BUT...",299.0,399.00,25.0,4.3
7,DELL Wireless Mouse Dell 3100,195.0,195.00,0.0,1.0
8,Gamdias Zeus E3 Gaming Optical Mouse And NYX E...,290.0,585.00,50.0,4.5
9,"ZERO ZR-2100 ZERO Gaming Mouse 3200 DPI, 6 BUT...",185.0,199.00,7.0,3.3

Check data after cleaning.

In [47]:
df.describe()

             Price    Old_Price  Discount_Percentage     Rating
count    80.000000    80.000000            80.000000  80.000000
mean    644.212750   872.427000            26.362500   1.785000
std     561.811681   701.535726            22.960199   2.239807
min      39.990000    80.000000             0.000000   0.000000
25%     268.750000   419.200000             0.000000   0.000000
50%     498.000000   652.000000            23.000000   0.000000
75%     793.100000  1048.272500            45.000000   4.500000
max    2859.000000  3299.000000            81.000000   5.000000

### Final Results

#### Product/s with maximum discount:

In [48]:
df[df['Discount_Percentage'] == df['Discount_Percentage'].max()]

,Product_Name,Price,Old_Price,Discount_Percentage,Rating
64,LED Backlight USB Wired Gamer Mouse M62 - Black,94.0,500.0,81.0,0.0
68,LED Backlight USB Wired Gamer Mouse M61 - Black,94.0,500.0,81.0,0.0

#### Product/s with maximum Price:

In [49]:
df[df['Price'] == df['Price'].max()]

,Product_Name,Price,Old_Price,Discount_Percentage,Rating
38,Logitech G305 LIGHTSPEED Wireless Gaming Mouse...,2859.0,3299.0,13.0,5.0

#### Product/s with minimum Price:

In [50]:
df[df['Price'] == df['Price'].min()]

,Product_Name,Price,Old_Price,Discount_Percentage,Rating
17,Razer Gaming Mouse Pad (250 X 210 X 2mm),39.99,80.0,50.0,4.5
28,Gaming Mouse Pad,39.99,100.0,60.0,4.4

#### Product/s with maximum Rating:

In [51]:
df[df['Rating'] == df['Rating'].max()]

,Product_Name,Price,Old_Price,Discount_Percentage,Rating
2,"HP Wireless Mouse, USB Charging, 1000 DB Senso...",250.0,499.0,50.0,5.0
11,Redragon M711 COBRA RGB Gaming Mouse - 10000 D...,920.0,1560.0,41.0,5.0
14,Redragon PHASER M609 GAMING MOUSE MULTI DPI SPEED,675.0,1200.0,44.0,5.0
27,T-Dagger T-TGM208 RGB Optical Gaming Mouse -64...,579.0,1000.0,42.0,5.0
29,T-Dagger Sergeant T-TGM202 Programmable Gaming...,750.0,975.0,23.0,5.0
31,T-Dagger T-TGM208 RGB Optical Gaming Mouse - ...,699.0,845.0,17.0,5.0
38,Logitech G305 LIGHTSPEED Wireless Gaming Mouse...,2859.0,3299.0,13.0,5.0
46,"HP Wireless Mouse, USB Charging, 1000 DB Senso...",250.0,499.0,50.0,5.0
48,Redragon M602-1 RGB Gaming Mouse - 7200DPI,879.0,1599.0,45.0,5.0
51,HP X220 Backlit Gaming Mouse Black,1449.0,1449.0,0.0,5.0
55,"Techno Zone V6 Gaming Mouse With 8 Keys ,12800dpi",875.0,1105.0,21.0,5.0
59,Microsoft Wireless Mobile Mouse 1850 - Dark Blue,1099.0,1334.0,18.0,5.0
74,Redragon M608 3200 DPI RGB Gaming Mouse - Black,850.0,1100.0,23.0,5.0